# # Be sure to restart your server when you modify this file.
#
# # Your secret key is used for verifying the integrity of signed cookies.
# # If you change this key, all old signed cookies will become invalid!
#
# # Make sure the secret is at least 30 characters and all random,
# # no regular words or you'll be exposed to dictionary attacks.
# # You can use `rails secret` to generate a secure secret key.
#
# # Make sure the secrets in this file are kept private
# # if you're sharing your code publicly.
#
# development:
#   secret_key_base: 30f9af6f686511bb1733514b3dfa0bb636b7517da0db49e737e31d25f8c21c265f90941a6c4671ee83d34ac19489aedc03db3d8bd60192de73101b2bed33bcb6
#
# test:
#   secret_key_base: 8162f65de6c9f0607656edd853d2ffa1771b4844724da408b20239cf8262404d84769ee40c1a1ce853604389cbd677a82d5175a610cf3b6483ec8a8fec60fb44
#
# # Do not keep production secrets in the repository,
# # instead read values from the environment.
# production:
#   secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>


development:
    secret_key_base: 30f9af6f686511bb1733514b3dfa0bb636b7517da0db49e737e31d25f8c21c265f90941a6c4671ee83d34ac19489aedc03db3d8bd60192de73101b2bed33bcb6
    cloudinary_cloud_name: <%= ENV["CLOUDINARY_CLOUD_NAME"] %>
    cloudinary_api_key: <%= ENV["CLOUDINARY_API_KEY"] %>
    cloudinary_api_secret: <%= ENV["CLOUDINARY_API_SECRET"] %>
test:
    secret_key_base: 8162f65de6c9f0607656edd853d2ffa1771b4844724da408b20239cf8262404d84769ee40c1a1ce853604389cbd677a82d5175a610cf3b6483ec8a8fec60fb44
    cloudinary_cloud_name: <%= ENV["CLOUDINARY_CLOUD_NAME"] %>
    cloudinary_api_key: <%= ENV["CLOUDINARY_API_KEY"] %>
    cloudinary_api_secret: <%= ENV["CLOUDINARY_API_SECRET"] %>
production:
    secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
    cloudinary_cloud_name: <%= ENV["CLOUDINARY_CLOUD_NAME"] %>
    cloudinary_api_key: <%= ENV["CLOUDINARY_API_KEY"] %>
    cloudinary_api_secret: <%= ENV["CLOUDINARY_API_SECRET"] %>
